In [5]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1


## Introduction to Tensors

### Creating Tensors

Pytorch tesnors are created using `torch.Tensor()` and the link is found here.

In [7]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [8]:
# scalar: no dimension and just a single number
scalar.ndim

0

In [9]:
scalar.item() # returns tensor as python int

7

## Vectors

They got a magnitude and direction and basically a list of numbers in pytorch. You can also create them using `torch.tensor`

In [10]:
#vector

vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [11]:
vector.ndim

1

In [12]:
vector.shape

torch.Size([2])

## MATRIX

They are basically a list that is two dimensional. You can also create them using  `torch.tensor()` with double brackets as you can see below

In [13]:
# MATRIX
MATRIX = torch.tensor([[7,8], [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [14]:
MATRIX.ndim

2

In [15]:
MATRIX[0]

tensor([7, 8])

In [16]:
MATRIX.shape

torch.Size([2, 2])

In [17]:
#TENSOR

TENSOR = torch.tensor([[[1,2,3], [3,6,9], [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [18]:
TENSOR.ndim #number of dimensions

3

In [19]:
TENSOR.shape

torch.Size([1, 3, 3])

In [20]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

## Random Tensors

WHy random tensors?

Random tensors are importsnt because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`


In [22]:
# Create a random tensors of size (3,4)

random_tensor = torch.rand(3,4) # 3 rows and 4 columns (2D)
random_tensor

tensor([[0.7016, 0.2451, 0.6284, 0.7297],
        [0.2724, 0.4314, 0.9865, 0.4586],
        [0.5792, 0.0158, 0.4356, 0.3901]])

In [23]:
random_tensor.ndim

2

In [26]:
# Create a random tesnor with a similar shape to an image tensor

# thats how colors are represented here

# you can put the size or not; same thing

random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, color channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and Ones

In [28]:
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

## You can zero out a non zero tensor by multiplying them with zero tensor

In [29]:
zero * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [30]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [31]:
ones.dtype

torch.float32

## Creating a range of tensors and tesnors-like

In [36]:
# torche.range() but with no deprectaed message use torch.arange()

one_to_ten = torch.arange(1,10,1) # starts at 1 finishes at 9 (third one is step)
one_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten) # basically creates the same array with the same shape but not the same elements
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**NOTE:** Tensor datayupes is one of the 3 bug errors you'll run into with pytorch and deep learning:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [45]:
# float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0], dtype=None,# data type is the type of the element like float32 or float16. float32 is the default even though its none above
                                device=None, #gpu device: when you have two tensors located on two different locations on computer, you will get an error. Like "cuda"
                                requires_grad=False) # whether or not to track gradients or not

float_32_tensor

tensor([3., 6., 9.])

In [43]:
float_32_tensor.dtype

torch.float32

In [47]:
float16_tensor = float_32_tensor.type(torch.float16) #convert into float16
float16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [48]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [49]:
float_32_tensor * int_32_tensor # worked? even though they have different data types

tensor([ 9., 36., 81.])

### Getting information from Tensors

1. Tensors not right data type - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - get shape from a tesnor, can use `tensor.shape`
3. Tensors not on the right device - get device from a tensor, can use `tensor.device`

In [53]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4112, 0.8893, 0.4071, 0.3285],
        [0.7682, 0.4113, 0.5669, 0.8467],
        [0.7565, 0.3087, 0.3051, 0.1891]])

In [51]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}") # default is cpu

tensor([[0.3749, 0.8649, 0.6938, 0.9004],
        [0.4336, 0.8110, 0.0790, 0.8965],
        [0.6312, 0.7764, 0.6091, 0.8422]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication
* Division
* Matrix Multiplication

In [54]:
# create a tensor and add 10 to it

tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [55]:
# multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [56]:
tensor

tensor([1, 2, 3])

In [57]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [58]:
# Try out pytorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [59]:
torch.add(tensor, 10)

tensor([11, 12, 13])

## Matrix Multiplication

Two main ways of performing multilpication in neural netowrks and deep learning:
1. Element-wise multiplication
2. Martix Multiplication (dot product)

In [60]:
# Element wise multiplication
tensor * tensor

tensor([1, 4, 9])

In [62]:
# Matrix Multiplication
torch.matmul(tensor, tensor) # THIS IS THE DOT PRODUCT

tensor(14)

In [64]:
import time

In [68]:
# Matrix Multiplication by hand
start_time = time.time()
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
end_time = time.time()
print(f"Execution time is {end_time - start_time}")
value

Execution time is 0.0010149478912353516


tensor(14)

In [71]:
start_time = time.time()
torch.matmul(tensor, tensor)
end_time = time.time()
print(f"Execution time is {end_time - start_time}")


Execution time is 0.0003352165222167969


### One of the most common errors in machine learning

There are two main rules that performing matrix multiplication needs to satsify:
1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(3,2) @ (2,3)` will work
* `(2,3) @ (3,2)` will work

`@` means dot product two things together.

2. The resulting matrix has the shape of the **outer dimensions**:

* `(2,3) @ (3,2) -> (2,2)` 
* `(3,2) @ (2,3) -> (3,3)` 





In [75]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.5758, 0.4029, 0.6496],
        [0.6061, 0.5977, 0.6786],
        [0.4017, 0.1280, 0.4579]])

In [86]:
# Shapes for matrix multiplication

tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [4,5]])
tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])

# torch.mm and torch.matmul is the same thing
# torch.matmul(tensor_A, tensor_B)

In [87]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix out our tensor shape issues, we can manipulate the shape of one of outr tensors using a **transpose**

A **transpose** switches the axes or dimensions fo a given tensor.

In [90]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [91]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [94]:
# The matrix multiplciation operation works when tensor_B is transposed

print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output: \n")
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")



Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
Original shapes: tensor_A = torch.Size([3, 2]), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output: 

tensor([[27, 30, 33],
        [61, 68, 75],
        [78, 87, 96]])

Output shape: torch.Size([3, 3])


## Finding tensor aggregation like min, max, mean, sum , etc.

In [98]:
# Create a tensor
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [96]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [97]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [102]:
# torch.mean function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [103]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [104]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [107]:
x.argmin() # the min is located at index 0 is what this means (find min, then returns index)

tensor(0)

In [110]:
x[0]

tensor(0)

In [108]:
# find the position in tensor that has the maxmimum value with argmax()
x.argmax()

tensor(9)

In [109]:
x[9]

tensor(90)

## Reshaping, stacking, squeezing, and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View -  Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other or side by side
* Squeeze - Removes all `1` dimensions from a tensor
* Unsqueeze -  Add a `1` dimenion to a target tensor
* Permute - Return a view of th einput with dimensions permuted (swapped) in a certain way

In [120]:
# Let's create a tensor
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [121]:
# Add extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [122]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [123]:
# Chaning z changes x (because a view of a tensor shares the same memory as the original tensor)
z[:, 0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [127]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [128]:
# torch.squeeze() - removes a single dimension from a target tensor
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [129]:
x_reshaped.shape

torch.Size([1, 9])

In [134]:
x_squeezed = x_reshaped.squeeze()

In [135]:
x_squeezed.shape

torch.Size([9])

In [140]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dimension 
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [149]:
#torch.permute - rearranges the dimensions in a specified order
x_unsqueezed.unsqueeze(dim=2).shape

torch.Size([1, 9, 1])

In [150]:
x_original = torch.rand(size=(224,224,3)) # [height, width, color_channels]
# permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) # shifts axis 

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [154]:
x_original[0,0,0]= 99
x_original[0,0,0], x_permuted[0,0,0] # as you can see, permuting is just a differnet view of the original part

(tensor(99.), tensor(99.))

### Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy.

In [155]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [156]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [157]:
# Let's index on the middle bracket
x[0][0]

tensor([1, 2, 3])

In [158]:
# Let's index on the most inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [159]:
# You can also use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [160]:
# Get all values of 0th and 1st dimensions but only 1 and 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [161]:
x[:,1,1]

tensor([5])

In [162]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [165]:
# Index on x to return 9
print(x[0,2,2])

#index on x to return 3,6,9

print(x[:, :, 2])

tensor(9)
tensor([[3, 6, 9]])


## PyTorch tensors and Numpy

Numpy is a popular scientific python numerical computing library.

And because of thism Pytorch has functionality to interact with it.

* Data in Numpy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [169]:
import torch 
import numpy as np

array = np.arange(1.0,8.0)
tensor =torch.from_numpy(array) # when converting from numpy -> pytorch, pytorch rflects numpy's default  datatype of float64 unless otherwise specified

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [167]:
array.dtype

dtype('float64')

In [168]:
torch.arange(1.0,8.0).dtype

torch.float32

In [170]:
array = array + 1
array, tensor # dont share the same memory

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [171]:
# Tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [172]:
# Change the tensor, what happens to numpy_tensor

tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short, how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data - > again -> again`

To reduce the randomness in neural netowrks and pytorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [174]:
torch.rand(3,3)

# create tow random tensors

random_tensor_1 = torch.rand(3,4)
random_tensor_2 = torch.rand(3,4)

print(random_tensor_1)
print(random_tensor_2)
print(random_tensor_1 == random_tensor_2)

tensor([[0.4198, 0.5804, 0.2778, 0.5991],
        [0.5830, 0.5498, 0.8430, 0.0019],
        [0.4764, 0.3651, 0.3990, 0.0715]])
tensor([[0.8287, 0.9945, 0.0929, 0.5288],
        [0.1035, 0.4545, 0.7895, 0.4351],
        [0.2398, 0.4630, 0.3687, 0.4719]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [177]:
# Let's make some random but reproducible tensors

# set the random seed

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_3 = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_4 = torch.rand(3,4) # we have to reset it each time we use this

print(random_tensor_3)
print(random_tensor_4)
print(random_tensor_3 == random_tensor_4)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and pytorch objects on the GPUs (and making faster computations)

GPUS = faster  computation on numbers, thanks to CUDA+NVIDIA hardware+Pytorch working behind the scenes to make things run much faster.

### 1. Getting a GPU

1. Easiest - Use google colab for a free GPU 

2. Use your own GPU - takes a litte but of setup and requires the invsetment of purchasing a GPU, there's lots of options.
3. Use cloud computing

### 2. Check for GPU access with PyTorch

In [179]:
# Check for GPU access with Pytorch
torch.cuda.is_available() # we got to donwload it

False

In [180]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device
  

'cpu'

In [181]:
# Count number of devices
torch.cuda.device_count()

0

## 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on teh GPU is because using a GPU results in faster computations.

In [182]:
# Create a tensor (default on the CPU)

tensor = torch.tensor([1,2,3])

# tensor on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [183]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device) # this will work regardless if the pc has cpu or gpu
tensor_on_gpu

tensor([1, 2, 3])

### 4. Moving tensors back to the CPU

In [184]:
# if tensor is on gpu, can't transform it to numpy
tensor_on_gpu.numpy() # this would not work if tensor is on gpu

array([1, 2, 3])

In [185]:
# to fix teh gpu tesnor with numpy issue, we can first set it to the cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])